services:
  # База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: procurement_db
    environment:
      POSTGRES_DB: ${DB_NAME:-diplom_db}
      POSTGRES_USER: ${DB_USER:-diplom_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_HOST_AUTH_METHOD: trust  # Только для разработки
      TZ: ${TZ:-Europe/Moscow}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # Директория для бэкапов
    ports:
      - "5432:5432"
    networks:
      - procurement_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-diplom_user}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Redis для Celery
  redis:
    image: redis:7-alpine
    container_name: procurement_redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - procurement_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Django приложение
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement_web
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=${TZ:-Europe/Moscow}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app/backend
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - logs_volume:/app/logs
      - ./data:/app/data:ro
    ports:
      - "8000:8000"
    networks:
      - procurement_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        until pg_isready -h db -U $${DB_USER:-diplom_user} -d $${DB_NAME:-diplom_db}; do
          echo 'Waiting for PostgreSQL...';
          sleep 2;
        done &&
        echo 'Running migrations...' &&
        python manage.py migrate --noinput &&
        echo 'Collecting static files...' &&
        python manage.py collectstatic --noinput &&
        echo 'Starting Gunicorn...' &&
        gunicorn --bind 0.0.0.0:8000 --workers 3 --worker-class gthread --threads 2 --timeout 60 --access-logfile - --error-logfile - --log-level info --worker-tmp-dir /dev/shm ProcurementDjango.wsgi:application
      "
    restart: unless-stopped

  # Celery Worker
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement_celery
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=${TZ:-Europe/Moscow}
      - PYTHONUNBUFFERED=1
    volumes:
      - logs_volume:/app/logs
      - ./data:/app/data:ro
    networks:
      - procurement_network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        until pg_isready -h db -U $${DB_USER:-diplom_user} -d $${DB_NAME:-diplom_db}; do
          echo 'Waiting for PostgreSQL...';
          sleep 2;
        done &&
        echo 'Starting Celery worker...' &&
        python -m celery -A ProcurementDjango worker --loglevel=info --concurrency=4 --max-tasks-per-child=100
      "
    restart: unless-stopped

  # Celery Beat (планировщик задач)
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procurement_celery_beat
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TZ=${TZ:-Europe/Moscow}
      - PYTHONUNBUFFERED=1
    volumes:
      - logs_volume:/app/logs
      - ./data:/app/data:ro
    networks:
      - procurement_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        until pg_isready -h db -U $${DB_USER:-diplom_user} -d $${DB_NAME:-diplom_db}; do
          echo 'Waiting for PostgreSQL...';
          sleep 2;
        done &&
        echo 'Starting Celery Beat...' &&
        python -m celery -A ProcurementDjango beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    restart: unless-stopped

  # Nginx для статических файлов
  nginx:
    image: nginx:alpine
    container_name: procurement_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - logs_volume:/var/log/nginx
    networks:
      - procurement_network
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
  logs_volume:

networks:
  procurement_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

