# Generated by Django 5.2.6 on 2025-10-25 09:04

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=backend.models.product_image_path, verbose_name='Изображение товара'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to=backend.models.user_avatar_path, verbose_name='Аватар'),
        ),
    ]
